#!/bin/bash

# The default google client. Works on both the ga and fsdf domains
GA_GOOGLE_CLIENT=client=gme-geoscienceaustralia
DEPLOY_DESTINATION=/var/www/water
WATER_WORK_DIR=/tmp/water_work

# Should be home already but make sure.
cd /home/ec2-user/elvis-water

# Update code base
git pull
# Pity there isn't an obvious way to only do this if there are changes. (Maybe check git history?)
bower update

# Is this the first time, if so make destination
test -d $DEPLOY_DESTINATION || sudo mkdir -p $DEPLOY_DESTINATION

# Copy static content to Apache
sudo cp -rf dist/* $DEPLOY_DESTINATION


# Sometimes you want to run it on a domain that does not have GA's Google client ID registered so
# you can set the system variable GOOGLE_KEY in your .bash_profile and export it so that
# it replace the GA key so something like
# export GOOGLE_KEY=key=some_valid_google_key
if [ -n "$GOOGLE_KEY" ]
then
  sudo rm -rf $WATER_WORK_DIR
  mkdir $WATER_WORK_DIR
  cp dist/*.html $WATER_WORK_DIR
  /bin/sed -i -e 's/'"$GA_GOOGLE_CLIENT"'/'"$GOOGLE_KEY"'/g' $WATER_WORK_DIR/*.html
  sudo cp -f $WATER_WORK_DIR/*.html /var/www/water
  sudo rm -rf $WATER_WORK_DIR
fi
